repos:
  - repo: local
    hooks:
      - id: rustfmt
        name: rustfmt
        entry: cargo fmt --all
        language: system
        files: \.(rs)$
      - id: clippy
        name: cargo clippy
        entry: cargo clippy --all-targets --all-features -- -D warnings
        language: system
        pass_filenames: false
      - id: buf-lint
        name: buf lint
        entry: buf lint
        language: system
        pass_filenames: false
      - id: helm-lint
        name: helm lint
        entry: helm lint charts/
        language: system
        pass_filenames: false

