[package]
name = "codex"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
prost = "0.11"
tonic = { version = "0.8", default-features = false, features = ["prost"] }

[build-dependencies]
tonic-build = "0.8"
