replicaCount: 1

image:
  repository: myrepo/taskd
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 50051

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
